### ISSUE TITLE
Protect staging environment

### ISSUE THREAD

**Issue by joonashak** [joonashak/holenav#128]
Staging environment has devtools enabled and as such should not be publicly accessible.

### TODO:

- [x] Create a middleware to require an additional secret key in headers. Activate and configure with an env var.
  - [x] Protect authenticated endpoints, and,
  - [x] devtools endpoints.
- [x] Modify client devtools to save the key in browser.
- [x] Use saved key in API requests.
