### ISSUE TITLE
Signature-connection-route trifecta

### ISSUE THREAD

**Issue by joonashak** [joonashak/holenav#135]
Epic-level issue for designing a proper architecture for signatures, wormhole connections and routing. I never felt comfortable with the previous solutions leading to this rubber duck of a ticket that will hopefully put my mind right.

# General

The general problem is traversing a two-way graph of wormhole connections. The nodes represent systems and the edges represent the connections between them.

While Mongo has awesome tooling and developer experience, it comes with only partial graph support making two-way graph traversals painful. A graph database is the native solution for this kind of problem but they come at the cost of complexity and a less-refined developer experience.

It would seem prudent to try and keep as much of the data structure as Mongoose models to leverage the same tooling as with the rest of the app. This maximizes code maintainability and minimizes the amount of critical code that is hard to maintain. Working with this idea, we would have the wormhole connections stored in Mongo and use `$graphLookup` to build trees from the connection graph. Doing this, we use only existing tooling and infrastructure (the aggregation result has to be manually typed, though). The big drawback is that `$graphLookup` can handle only one-way relations meaning we must maintain duplicate connection documents to implement a two-way graph.

Considering only the operation of traversing the connection graph to build a tree map view, it would seem that a graph database has little to offer besides a native two-way link, i.e., not having to maintain duplicate connection documents. Mongo's performance is likely more than enough for the graph lookup operations at Holenav's scale and is easily further enhanced with Nest's caching.

However, I find playing around with a graph database very interesting and there might be a legit use case for it – routing. With some quick googling, it seems that there are around 7,500 systems and 14,000 stargate connections in EVE. This, too, might be well within Mongo's capabilities. It would be interesting to compare, e.g., Mongo and dgraph with this problem. Routing could be implemented as an optional feature in Holenav, especially if it uses different techniques making maintenance harder, etc.

# Design

## Signatures

The `Signature` model should be similar to the in-game _Cosmic Signature_ which it represents. Wormhole-type signatures should not contain any connection information other than linking to the respective `Connection` object.

## Wormhole Connections

The `Connection` model represents a wormhole connection.

- `Connection.origin` is always the system where the related signature is.
- `Connection.destination` can be `null`. This is required because mass, EOL, and other properties must be saved also for connection to unknown destinations.
- Due to limitations of Mongo's `$graphLookup`, a duplicate `Connection` in the reverse direction is required for the graph to be traversable in any direction. Maintaining duplicate connection documents is perhaps the biggest drawback of using Mongo to store the connections.

# TODO

## Signatures

- [x] Store signatures in Mongo (currently only GraphQL model in use after Neo4j era). Signature mutations should be the primary drivers for `Connection` mutations.
  - [x] Create
  - [x] Update
  - [x] Delete
- [x] Signature maintenance service to clean up old signatures and expired connections.
- [x] Access control.
- [x] Reverse connection signatures.
- [x] 🐛 Allow empty `eveId` (reverse connections' sigs need this).

## Connections

- [x] `Connection` model.
- [x] `ConnectionService` methods to maintain reverse connections robustly.
- [x] `ConnectionGraphService` for generating maps using graph lookup.
- [x] `ConnectionGraphResolver` for querying maps. Due to GraphQL limitations with recursion, maps should be flat lists and transformation to tree structure done at client-side.
  - [x] Current implementation passes the full set of graph nodes for each chain. Remove duplicates to reduce response size.
- [ ] Test edge cases:
  - [x] Loops, also multiple.
  - [x] Unknown destinations.
  - [ ] Very big trees, both wide and deep.
- [x] Access control.
- [x] Implement `eolAt` field.
- [x] 🐛 `unknown` field is not set correctly.

## Other

- [x] Seed some good maps with dev tools.
- [x] Integration tests for combined `SignatureService` and `ConnectionService` operations.
