### ISSUE TITLE
Map graph rework

### ISSUE THREAD

**Issue by joonashak** [joonashak/holenav#138]
# TODO

- [x] Remove `react-d3-tree` and old map graph code.
- [x] Install React Flow 🎉 
- [x] Implement basic map structure as a static tree.
- [ ] Custom nodes with system info.
- [ ] Custom edges with connection info.
- [ ] Hide UUID system names.
- [ ] Show loops nicely.
- [ ] Style with MUI.
